//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookARoom.ServiceReferenceBookARoom {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid BookingNumberField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoom.ServiceReferenceBookARoom.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoom.ServiceReferenceBookARoom.Room RoomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid BookingNumber {
            get {
                return this.BookingNumberField;
            }
            set {
                if ((this.BookingNumberField.Equals(value) != true)) {
                    this.BookingNumberField = value;
                    this.RaisePropertyChanged("BookingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CEmail {
            get {
                return this.CEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CEmailField, value) != true)) {
                    this.CEmailField = value;
                    this.RaisePropertyChanged("CEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public BookARoom.ServiceReferenceBookARoom.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BookARoom.ServiceReferenceBookARoom.Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Booking> BookingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CPhoneNumber {
            get {
                return this.CPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CPhoneNumberField, value) != true)) {
                    this.CPhoneNumberField = value;
                    this.RaisePropertyChanged("CPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CName {
            get {
                return this.CNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNameField, value) != true)) {
                    this.CNameField = value;
                    this.RaisePropertyChanged("CName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CAdress {
            get {
                return this.CAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.CAdressField, value) != true)) {
                    this.CAdressField = value;
                    this.RaisePropertyChanged("CAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CEmail {
            get {
                return this.CEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CEmailField, value) != true)) {
                    this.CEmailField = value;
                    this.RaisePropertyChanged("CEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Booking> Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedField;
        
        private bool SmokeFreeField;
        
        private int PriceField;
        
        private int GuestCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoom.ServiceReferenceBookARoom.Hotel HotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Booking> BookingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Bed {
            get {
                return this.BedField;
            }
            set {
                if ((object.ReferenceEquals(this.BedField, value) != true)) {
                    this.BedField = value;
                    this.RaisePropertyChanged("Bed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool SmokeFree {
            get {
                return this.SmokeFreeField;
            }
            set {
                if ((this.SmokeFreeField.Equals(value) != true)) {
                    this.SmokeFreeField = value;
                    this.RaisePropertyChanged("SmokeFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GuestCapacity {
            get {
                return this.GuestCapacityField;
            }
            set {
                if ((this.GuestCapacityField.Equals(value) != true)) {
                    this.GuestCapacityField = value;
                    this.RaisePropertyChanged("GuestCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BookARoom.ServiceReferenceBookARoom.Hotel Hotel {
            get {
                return this.HotelField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelField, value) != true)) {
                    this.HotelField = value;
                    this.RaisePropertyChanged("Hotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Booking> Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountrynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoom.ServiceReferenceBookARoom.City CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Room> RoomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Standard {
            get {
                return this.StandardField;
            }
            set {
                if ((object.ReferenceEquals(this.StandardField, value) != true)) {
                    this.StandardField = value;
                    this.RaisePropertyChanged("Standard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Countryname {
            get {
                return this.CountrynameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountrynameField, value) != true)) {
                    this.CountrynameField = value;
                    this.RaisePropertyChanged("Countryname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BookARoom.ServiceReferenceBookARoom.City City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Room> Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Hotel> HotelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Hotel> Hotels {
            get {
                return this.HotelsField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelsField, value) != true)) {
                    this.HotelsField = value;
                    this.RaisePropertyChanged("Hotels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBookARoom.BookARoomWebServiceSoap")]
    public interface BookARoomWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllBookingsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBookings", ReplyAction="*")]
        BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponse GetAllBookings(BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponse> GetAllBookingsAsync(BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllRoomsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRooms", ReplyAction="*")]
        BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponse GetAllRooms(BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponse> GetAllRoomsAsync(BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCitiesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCities", ReplyAction="*")]
        BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponse GetAllCities(BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCities", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponse> GetAllCitiesAsync(BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllHotelsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllHotels", ReplyAction="*")]
        BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponse GetAllHotels(BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponse> GetAllHotelsAsync(BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomers", ReplyAction="*")]
        BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponse GetAllCustomers(BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponse> GetAllCustomersAsync(BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookings", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequestBody Body;
        
        public GetAllBookingsRequest() {
        }
        
        public GetAllBookingsRequest(BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllBookingsRequestBody {
        
        public GetAllBookingsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponseBody Body;
        
        public GetAllBookingsResponse() {
        }
        
        public GetAllBookingsResponse(BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Booking> GetAllBookingsResult;
        
        public GetAllBookingsResponseBody() {
        }
        
        public GetAllBookingsResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Booking> GetAllBookingsResult) {
            this.GetAllBookingsResult = GetAllBookingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRooms", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequestBody Body;
        
        public GetAllRoomsRequest() {
        }
        
        public GetAllRoomsRequest(BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRoomsRequestBody {
        
        public GetAllRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponseBody Body;
        
        public GetAllRoomsResponse() {
        }
        
        public GetAllRoomsResponse(BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Room> GetAllRoomsResult;
        
        public GetAllRoomsResponseBody() {
        }
        
        public GetAllRoomsResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Room> GetAllRoomsResult) {
            this.GetAllRoomsResult = GetAllRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCities", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequestBody Body;
        
        public GetAllCitiesRequest() {
        }
        
        public GetAllCitiesRequest(BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCitiesRequestBody {
        
        public GetAllCitiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCitiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponseBody Body;
        
        public GetAllCitiesResponse() {
        }
        
        public GetAllCitiesResponse(BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.City> GetAllCitiesResult;
        
        public GetAllCitiesResponseBody() {
        }
        
        public GetAllCitiesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.City> GetAllCitiesResult) {
            this.GetAllCitiesResult = GetAllCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllHotelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllHotels", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequestBody Body;
        
        public GetAllHotelsRequest() {
        }
        
        public GetAllHotelsRequest(BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllHotelsRequestBody {
        
        public GetAllHotelsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllHotelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllHotelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponseBody Body;
        
        public GetAllHotelsResponse() {
        }
        
        public GetAllHotelsResponse(BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllHotelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Hotel> GetAllHotelsResult;
        
        public GetAllHotelsResponseBody() {
        }
        
        public GetAllHotelsResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Hotel> GetAllHotelsResult) {
            this.GetAllHotelsResult = GetAllHotelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomers", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequestBody Body;
        
        public GetAllCustomersRequest() {
        }
        
        public GetAllCustomersRequest(BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCustomersRequestBody {
        
        public GetAllCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponseBody Body;
        
        public GetAllCustomersResponse() {
        }
        
        public GetAllCustomersResponse(BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Customer> GetAllCustomersResult;
        
        public GetAllCustomersResponseBody() {
        }
        
        public GetAllCustomersResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Customer> GetAllCustomersResult) {
            this.GetAllCustomersResult = GetAllCustomersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookARoomWebServiceSoapChannel : BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookARoomWebServiceSoapClient : System.ServiceModel.ClientBase<BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap>, BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap {
        
        public BookARoomWebServiceSoapClient() {
        }
        
        public BookARoomWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookARoomWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookARoomWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookARoomWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponse BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllBookings(BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest request) {
            return base.Channel.GetAllBookings(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Booking> GetAllBookings() {
            BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequestBody();
            BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponse retVal = ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllBookings(inValue);
            return retVal.Body.GetAllBookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponse> BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllBookingsAsync(BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest request) {
            return base.Channel.GetAllBookingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllBookingsResponse> GetAllBookingsAsync() {
            BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllBookingsRequestBody();
            return ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllBookingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponse BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllRooms(BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest request) {
            return base.Channel.GetAllRooms(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Room> GetAllRooms() {
            BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequestBody();
            BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponse retVal = ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllRooms(inValue);
            return retVal.Body.GetAllRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponse> BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllRoomsAsync(BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest request) {
            return base.Channel.GetAllRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllRoomsResponse> GetAllRoomsAsync() {
            BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllRoomsRequestBody();
            return ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponse BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllCities(BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest request) {
            return base.Channel.GetAllCities(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.City> GetAllCities() {
            BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequestBody();
            BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponse retVal = ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllCities(inValue);
            return retVal.Body.GetAllCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponse> BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllCitiesAsync(BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest request) {
            return base.Channel.GetAllCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllCitiesResponse> GetAllCitiesAsync() {
            BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllCitiesRequestBody();
            return ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponse BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllHotels(BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest request) {
            return base.Channel.GetAllHotels(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Hotel> GetAllHotels() {
            BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequestBody();
            BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponse retVal = ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllHotels(inValue);
            return retVal.Body.GetAllHotelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponse> BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllHotelsAsync(BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest request) {
            return base.Channel.GetAllHotelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllHotelsResponse> GetAllHotelsAsync() {
            BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllHotelsRequestBody();
            return ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllHotelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponse BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllCustomers(BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomers(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceBookARoom.Customer> GetAllCustomers() {
            BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequestBody();
            BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponse retVal = ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllCustomers(inValue);
            return retVal.Body.GetAllCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponse> BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap.GetAllCustomersAsync(BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceBookARoom.GetAllCustomersResponse> GetAllCustomersAsync() {
            BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest inValue = new BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequest();
            inValue.Body = new BookARoom.ServiceReferenceBookARoom.GetAllCustomersRequestBody();
            return ((BookARoom.ServiceReferenceBookARoom.BookARoomWebServiceSoap)(this)).GetAllCustomersAsync(inValue);
        }
    }
}
