//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookARoom.ServiceReferenceFile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceFile.WebServiceUppgift2__1Soap")]
    public interface WebServiceUppgift2__1Soap {
        
        // CODEGEN: Generating message contract since element name GetFileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        BookARoom.ServiceReferenceFile.GetFileResponse GetFile(BookARoom.ServiceReferenceFile.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceFile.GetFileResponse> GetFileAsync(BookARoom.ServiceReferenceFile.GetFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceFile.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(BookARoom.ServiceReferenceFile.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFileRequestBody {
        
        public GetFileRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceFile.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(BookARoom.ServiceReferenceFile.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(string GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUppgift2__1SoapChannel : BookARoom.ServiceReferenceFile.WebServiceUppgift2__1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUppgift2__1SoapClient : System.ServiceModel.ClientBase<BookARoom.ServiceReferenceFile.WebServiceUppgift2__1Soap>, BookARoom.ServiceReferenceFile.WebServiceUppgift2__1Soap {
        
        public WebServiceUppgift2__1SoapClient() {
        }
        
        public WebServiceUppgift2__1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUppgift2__1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUppgift2__1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUppgift2__1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceFile.GetFileResponse BookARoom.ServiceReferenceFile.WebServiceUppgift2__1Soap.GetFile(BookARoom.ServiceReferenceFile.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public string GetFile() {
            BookARoom.ServiceReferenceFile.GetFileRequest inValue = new BookARoom.ServiceReferenceFile.GetFileRequest();
            inValue.Body = new BookARoom.ServiceReferenceFile.GetFileRequestBody();
            BookARoom.ServiceReferenceFile.GetFileResponse retVal = ((BookARoom.ServiceReferenceFile.WebServiceUppgift2__1Soap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceFile.GetFileResponse> BookARoom.ServiceReferenceFile.WebServiceUppgift2__1Soap.GetFileAsync(BookARoom.ServiceReferenceFile.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceFile.GetFileResponse> GetFileAsync() {
            BookARoom.ServiceReferenceFile.GetFileRequest inValue = new BookARoom.ServiceReferenceFile.GetFileRequest();
            inValue.Body = new BookARoom.ServiceReferenceFile.GetFileRequestBody();
            return ((BookARoom.ServiceReferenceFile.WebServiceUppgift2__1Soap)(this)).GetFileAsync(inValue);
        }
    }
}
