//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookARoom.ServiceReferenceCronus {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCronus.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeTables", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponse GetEmployeeTables(BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeTables", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponse> GetEmployeeTablesAsync(BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeTablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeTables", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequestBody Body;
        
        public GetEmployeeTablesRequest() {
        }
        
        public GetEmployeeTablesRequest(BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeTablesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public GetEmployeeTablesRequestBody() {
        }
        
        public GetEmployeeTablesRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeTablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeTablesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponseBody Body;
        
        public GetEmployeeTablesResponse() {
        }
        
        public GetEmployeeTablesResponse(BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeTablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus.ArrayOfString> GetEmployeeTablesResult;
        
        public GetEmployeeTablesResponseBody() {
        }
        
        public GetEmployeeTablesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus.ArrayOfString> GetEmployeeTablesResult) {
            this.GetEmployeeTablesResult = GetEmployeeTablesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BookARoom.ServiceReferenceCronus.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BookARoom.ServiceReferenceCronus.ServiceSoap>, BookARoom.ServiceReferenceCronus.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponse BookARoom.ServiceReferenceCronus.ServiceSoap.GetEmployeeTables(BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest request) {
            return base.Channel.GetEmployeeTables(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus.ArrayOfString> GetEmployeeTables(string tableName) {
            BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest inValue = new BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequestBody();
            inValue.Body.tableName = tableName;
            BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponse retVal = ((BookARoom.ServiceReferenceCronus.ServiceSoap)(this)).GetEmployeeTables(inValue);
            return retVal.Body.GetEmployeeTablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponse> BookARoom.ServiceReferenceCronus.ServiceSoap.GetEmployeeTablesAsync(BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest request) {
            return base.Channel.GetEmployeeTablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus.GetEmployeeTablesResponse> GetEmployeeTablesAsync(string tableName) {
            BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest inValue = new BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus.GetEmployeeTablesRequestBody();
            inValue.Body.tableName = tableName;
            return ((BookARoom.ServiceReferenceCronus.ServiceSoap)(this)).GetEmployeeTablesAsync(inValue);
        }
    }
}
