//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookARoomClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid BookingNumberField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.Room RoomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid BookingNumber {
            get {
                return this.BookingNumberField;
            }
            set {
                if ((this.BookingNumberField.Equals(value) != true)) {
                    this.BookingNumberField = value;
                    this.RaisePropertyChanged("BookingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CEmail {
            get {
                return this.CEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CEmailField, value) != true)) {
                    this.CEmailField = value;
                    this.RaisePropertyChanged("CEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public BookARoomClient.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BookARoomClient.ServiceReference1.Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.Booking[] BookingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CPhoneNumber {
            get {
                return this.CPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CPhoneNumberField, value) != true)) {
                    this.CPhoneNumberField = value;
                    this.RaisePropertyChanged("CPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CName {
            get {
                return this.CNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNameField, value) != true)) {
                    this.CNameField = value;
                    this.RaisePropertyChanged("CName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CAdress {
            get {
                return this.CAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.CAdressField, value) != true)) {
                    this.CAdressField = value;
                    this.RaisePropertyChanged("CAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CEmail {
            get {
                return this.CEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CEmailField, value) != true)) {
                    this.CEmailField = value;
                    this.RaisePropertyChanged("CEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BookARoomClient.ServiceReference1.Booking[] Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedField;
        
        private bool SmokeFreeField;
        
        private int PriceField;
        
        private int GuestCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.Hotel HotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.Booking[] BookingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Bed {
            get {
                return this.BedField;
            }
            set {
                if ((object.ReferenceEquals(this.BedField, value) != true)) {
                    this.BedField = value;
                    this.RaisePropertyChanged("Bed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool SmokeFree {
            get {
                return this.SmokeFreeField;
            }
            set {
                if ((this.SmokeFreeField.Equals(value) != true)) {
                    this.SmokeFreeField = value;
                    this.RaisePropertyChanged("SmokeFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GuestCapacity {
            get {
                return this.GuestCapacityField;
            }
            set {
                if ((this.GuestCapacityField.Equals(value) != true)) {
                    this.GuestCapacityField = value;
                    this.RaisePropertyChanged("GuestCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BookARoomClient.ServiceReference1.Hotel Hotel {
            get {
                return this.HotelField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelField, value) != true)) {
                    this.HotelField = value;
                    this.RaisePropertyChanged("Hotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public BookARoomClient.ServiceReference1.Booking[] Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountrynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.City CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.Room[] RoomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Standard {
            get {
                return this.StandardField;
            }
            set {
                if ((object.ReferenceEquals(this.StandardField, value) != true)) {
                    this.StandardField = value;
                    this.RaisePropertyChanged("Standard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Countryname {
            get {
                return this.CountrynameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountrynameField, value) != true)) {
                    this.CountrynameField = value;
                    this.RaisePropertyChanged("Countryname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BookARoomClient.ServiceReference1.City City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public BookARoomClient.ServiceReference1.Room[] Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookARoomClient.ServiceReference1.Hotel[] HotelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BookARoomClient.ServiceReference1.Hotel[] Hotels {
            get {
                return this.HotelsField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelsField, value) != true)) {
                    this.HotelsField = value;
                    this.RaisePropertyChanged("Hotels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BookARoomWebServiceSoap")]
    public interface BookARoomWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name selectedTable from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBookings", ReplyAction="*")]
        BookARoomClient.ServiceReference1.GetAllBookingsResponse GetAllBookings(BookARoomClient.ServiceReference1.GetAllBookingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllBookingsResponse> GetAllBookingsAsync(BookARoomClient.ServiceReference1.GetAllBookingsRequest request);
        
        // CODEGEN: Generating message contract since element name selectedTable from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRooms", ReplyAction="*")]
        BookARoomClient.ServiceReference1.GetAllRoomsResponse GetAllRooms(BookARoomClient.ServiceReference1.GetAllRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllRoomsResponse> GetAllRoomsAsync(BookARoomClient.ServiceReference1.GetAllRoomsRequest request);
        
        // CODEGEN: Generating message contract since element name selectedTable from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCities", ReplyAction="*")]
        BookARoomClient.ServiceReference1.GetAllCitiesResponse GetAllCities(BookARoomClient.ServiceReference1.GetAllCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCities", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllCitiesResponse> GetAllCitiesAsync(BookARoomClient.ServiceReference1.GetAllCitiesRequest request);
        
        // CODEGEN: Generating message contract since element name selectedTable from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllHotels", ReplyAction="*")]
        BookARoomClient.ServiceReference1.GetAllHotelsResponse GetAllHotels(BookARoomClient.ServiceReference1.GetAllHotelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllHotelsResponse> GetAllHotelsAsync(BookARoomClient.ServiceReference1.GetAllHotelsRequest request);
        
        // CODEGEN: Generating message contract since element name selectedTable from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomers", ReplyAction="*")]
        BookARoomClient.ServiceReference1.GetAllCustomersResponse GetAllCustomers(BookARoomClient.ServiceReference1.GetAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllCustomersResponse> GetAllCustomersAsync(BookARoomClient.ServiceReference1.GetAllCustomersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookings", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllBookingsRequestBody Body;
        
        public GetAllBookingsRequest() {
        }
        
        public GetAllBookingsRequest(BookARoomClient.ServiceReference1.GetAllBookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBookingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedTable;
        
        public GetAllBookingsRequestBody() {
        }
        
        public GetAllBookingsRequestBody(string selectedTable) {
            this.selectedTable = selectedTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllBookingsResponseBody Body;
        
        public GetAllBookingsResponse() {
        }
        
        public GetAllBookingsResponse(BookARoomClient.ServiceReference1.GetAllBookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookARoomClient.ServiceReference1.Booking[] GetAllBookingsResult;
        
        public GetAllBookingsResponseBody() {
        }
        
        public GetAllBookingsResponseBody(BookARoomClient.ServiceReference1.Booking[] GetAllBookingsResult) {
            this.GetAllBookingsResult = GetAllBookingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRooms", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllRoomsRequestBody Body;
        
        public GetAllRoomsRequest() {
        }
        
        public GetAllRoomsRequest(BookARoomClient.ServiceReference1.GetAllRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRoomsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedTable;
        
        public GetAllRoomsRequestBody() {
        }
        
        public GetAllRoomsRequestBody(string selectedTable) {
            this.selectedTable = selectedTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllRoomsResponseBody Body;
        
        public GetAllRoomsResponse() {
        }
        
        public GetAllRoomsResponse(BookARoomClient.ServiceReference1.GetAllRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookARoomClient.ServiceReference1.Room[] GetAllRoomsResult;
        
        public GetAllRoomsResponseBody() {
        }
        
        public GetAllRoomsResponseBody(BookARoomClient.ServiceReference1.Room[] GetAllRoomsResult) {
            this.GetAllRoomsResult = GetAllRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCities", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllCitiesRequestBody Body;
        
        public GetAllCitiesRequest() {
        }
        
        public GetAllCitiesRequest(BookARoomClient.ServiceReference1.GetAllCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCitiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedTable;
        
        public GetAllCitiesRequestBody() {
        }
        
        public GetAllCitiesRequestBody(string selectedTable) {
            this.selectedTable = selectedTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCitiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllCitiesResponseBody Body;
        
        public GetAllCitiesResponse() {
        }
        
        public GetAllCitiesResponse(BookARoomClient.ServiceReference1.GetAllCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookARoomClient.ServiceReference1.City[] GetAllCitiesResult;
        
        public GetAllCitiesResponseBody() {
        }
        
        public GetAllCitiesResponseBody(BookARoomClient.ServiceReference1.City[] GetAllCitiesResult) {
            this.GetAllCitiesResult = GetAllCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllHotelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllHotels", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllHotelsRequestBody Body;
        
        public GetAllHotelsRequest() {
        }
        
        public GetAllHotelsRequest(BookARoomClient.ServiceReference1.GetAllHotelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllHotelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedTable;
        
        public GetAllHotelsRequestBody() {
        }
        
        public GetAllHotelsRequestBody(string selectedTable) {
            this.selectedTable = selectedTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllHotelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllHotelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllHotelsResponseBody Body;
        
        public GetAllHotelsResponse() {
        }
        
        public GetAllHotelsResponse(BookARoomClient.ServiceReference1.GetAllHotelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllHotelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookARoomClient.ServiceReference1.Hotel[] GetAllHotelsResult;
        
        public GetAllHotelsResponseBody() {
        }
        
        public GetAllHotelsResponseBody(BookARoomClient.ServiceReference1.Hotel[] GetAllHotelsResult) {
            this.GetAllHotelsResult = GetAllHotelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomers", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllCustomersRequestBody Body;
        
        public GetAllCustomersRequest() {
        }
        
        public GetAllCustomersRequest(BookARoomClient.ServiceReference1.GetAllCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCustomersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedTable;
        
        public GetAllCustomersRequestBody() {
        }
        
        public GetAllCustomersRequestBody(string selectedTable) {
            this.selectedTable = selectedTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoomClient.ServiceReference1.GetAllCustomersResponseBody Body;
        
        public GetAllCustomersResponse() {
        }
        
        public GetAllCustomersResponse(BookARoomClient.ServiceReference1.GetAllCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookARoomClient.ServiceReference1.Customer[] GetAllCustomersResult;
        
        public GetAllCustomersResponseBody() {
        }
        
        public GetAllCustomersResponseBody(BookARoomClient.ServiceReference1.Customer[] GetAllCustomersResult) {
            this.GetAllCustomersResult = GetAllCustomersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookARoomWebServiceSoapChannel : BookARoomClient.ServiceReference1.BookARoomWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookARoomWebServiceSoapClient : System.ServiceModel.ClientBase<BookARoomClient.ServiceReference1.BookARoomWebServiceSoap>, BookARoomClient.ServiceReference1.BookARoomWebServiceSoap {
        
        public BookARoomWebServiceSoapClient() {
        }
        
        public BookARoomWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookARoomWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookARoomWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookARoomWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoomClient.ServiceReference1.GetAllBookingsResponse BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllBookings(BookARoomClient.ServiceReference1.GetAllBookingsRequest request) {
            return base.Channel.GetAllBookings(request);
        }
        
        public BookARoomClient.ServiceReference1.Booking[] GetAllBookings(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllBookingsRequest inValue = new BookARoomClient.ServiceReference1.GetAllBookingsRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllBookingsRequestBody();
            inValue.Body.selectedTable = selectedTable;
            BookARoomClient.ServiceReference1.GetAllBookingsResponse retVal = ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllBookings(inValue);
            return retVal.Body.GetAllBookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllBookingsResponse> BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllBookingsAsync(BookARoomClient.ServiceReference1.GetAllBookingsRequest request) {
            return base.Channel.GetAllBookingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllBookingsResponse> GetAllBookingsAsync(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllBookingsRequest inValue = new BookARoomClient.ServiceReference1.GetAllBookingsRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllBookingsRequestBody();
            inValue.Body.selectedTable = selectedTable;
            return ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllBookingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoomClient.ServiceReference1.GetAllRoomsResponse BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllRooms(BookARoomClient.ServiceReference1.GetAllRoomsRequest request) {
            return base.Channel.GetAllRooms(request);
        }
        
        public BookARoomClient.ServiceReference1.Room[] GetAllRooms(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllRoomsRequest inValue = new BookARoomClient.ServiceReference1.GetAllRoomsRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllRoomsRequestBody();
            inValue.Body.selectedTable = selectedTable;
            BookARoomClient.ServiceReference1.GetAllRoomsResponse retVal = ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllRooms(inValue);
            return retVal.Body.GetAllRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllRoomsResponse> BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllRoomsAsync(BookARoomClient.ServiceReference1.GetAllRoomsRequest request) {
            return base.Channel.GetAllRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllRoomsResponse> GetAllRoomsAsync(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllRoomsRequest inValue = new BookARoomClient.ServiceReference1.GetAllRoomsRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllRoomsRequestBody();
            inValue.Body.selectedTable = selectedTable;
            return ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoomClient.ServiceReference1.GetAllCitiesResponse BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllCities(BookARoomClient.ServiceReference1.GetAllCitiesRequest request) {
            return base.Channel.GetAllCities(request);
        }
        
        public BookARoomClient.ServiceReference1.City[] GetAllCities(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllCitiesRequest inValue = new BookARoomClient.ServiceReference1.GetAllCitiesRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllCitiesRequestBody();
            inValue.Body.selectedTable = selectedTable;
            BookARoomClient.ServiceReference1.GetAllCitiesResponse retVal = ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllCities(inValue);
            return retVal.Body.GetAllCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllCitiesResponse> BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllCitiesAsync(BookARoomClient.ServiceReference1.GetAllCitiesRequest request) {
            return base.Channel.GetAllCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllCitiesResponse> GetAllCitiesAsync(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllCitiesRequest inValue = new BookARoomClient.ServiceReference1.GetAllCitiesRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllCitiesRequestBody();
            inValue.Body.selectedTable = selectedTable;
            return ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoomClient.ServiceReference1.GetAllHotelsResponse BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllHotels(BookARoomClient.ServiceReference1.GetAllHotelsRequest request) {
            return base.Channel.GetAllHotels(request);
        }
        
        public BookARoomClient.ServiceReference1.Hotel[] GetAllHotels(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllHotelsRequest inValue = new BookARoomClient.ServiceReference1.GetAllHotelsRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllHotelsRequestBody();
            inValue.Body.selectedTable = selectedTable;
            BookARoomClient.ServiceReference1.GetAllHotelsResponse retVal = ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllHotels(inValue);
            return retVal.Body.GetAllHotelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllHotelsResponse> BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllHotelsAsync(BookARoomClient.ServiceReference1.GetAllHotelsRequest request) {
            return base.Channel.GetAllHotelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllHotelsResponse> GetAllHotelsAsync(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllHotelsRequest inValue = new BookARoomClient.ServiceReference1.GetAllHotelsRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllHotelsRequestBody();
            inValue.Body.selectedTable = selectedTable;
            return ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllHotelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoomClient.ServiceReference1.GetAllCustomersResponse BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllCustomers(BookARoomClient.ServiceReference1.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomers(request);
        }
        
        public BookARoomClient.ServiceReference1.Customer[] GetAllCustomers(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllCustomersRequest inValue = new BookARoomClient.ServiceReference1.GetAllCustomersRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllCustomersRequestBody();
            inValue.Body.selectedTable = selectedTable;
            BookARoomClient.ServiceReference1.GetAllCustomersResponse retVal = ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllCustomers(inValue);
            return retVal.Body.GetAllCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllCustomersResponse> BookARoomClient.ServiceReference1.BookARoomWebServiceSoap.GetAllCustomersAsync(BookARoomClient.ServiceReference1.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoomClient.ServiceReference1.GetAllCustomersResponse> GetAllCustomersAsync(string selectedTable) {
            BookARoomClient.ServiceReference1.GetAllCustomersRequest inValue = new BookARoomClient.ServiceReference1.GetAllCustomersRequest();
            inValue.Body = new BookARoomClient.ServiceReference1.GetAllCustomersRequestBody();
            inValue.Body.selectedTable = selectedTable;
            return ((BookARoomClient.ServiceReference1.BookARoomWebServiceSoap)(this)).GetAllCustomersAsync(inValue);
        }
    }
}
