//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookARoom.ServiceReferenceUppg2_1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUppg2_1.WSUppgift2Soap")]
    public interface WSUppgift2Soap {
        
        // CODEGEN: Generating message contract since element name GetFileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        BookARoom.ServiceReferenceUppg2_1.GetFileResponse GetFile(BookARoom.ServiceReferenceUppg2_1.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceUppg2_1.GetFileResponse> GetFileAsync(BookARoom.ServiceReferenceUppg2_1.GetFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceUppg2_1.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(BookARoom.ServiceReferenceUppg2_1.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFileRequestBody {
        
        public GetFileRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceUppg2_1.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(BookARoom.ServiceReferenceUppg2_1.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(string GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSUppgift2SoapChannel : BookARoom.ServiceReferenceUppg2_1.WSUppgift2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSUppgift2SoapClient : System.ServiceModel.ClientBase<BookARoom.ServiceReferenceUppg2_1.WSUppgift2Soap>, BookARoom.ServiceReferenceUppg2_1.WSUppgift2Soap {
        
        public WSUppgift2SoapClient() {
        }
        
        public WSUppgift2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSUppgift2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUppgift2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUppgift2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceUppg2_1.GetFileResponse BookARoom.ServiceReferenceUppg2_1.WSUppgift2Soap.GetFile(BookARoom.ServiceReferenceUppg2_1.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public string GetFile() {
            BookARoom.ServiceReferenceUppg2_1.GetFileRequest inValue = new BookARoom.ServiceReferenceUppg2_1.GetFileRequest();
            inValue.Body = new BookARoom.ServiceReferenceUppg2_1.GetFileRequestBody();
            BookARoom.ServiceReferenceUppg2_1.GetFileResponse retVal = ((BookARoom.ServiceReferenceUppg2_1.WSUppgift2Soap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceUppg2_1.GetFileResponse> BookARoom.ServiceReferenceUppg2_1.WSUppgift2Soap.GetFileAsync(BookARoom.ServiceReferenceUppg2_1.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceUppg2_1.GetFileResponse> GetFileAsync() {
            BookARoom.ServiceReferenceUppg2_1.GetFileRequest inValue = new BookARoom.ServiceReferenceUppg2_1.GetFileRequest();
            inValue.Body = new BookARoom.ServiceReferenceUppg2_1.GetFileRequestBody();
            return ((BookARoom.ServiceReferenceUppg2_1.WSUppgift2Soap)(this)).GetFileAsync(inValue);
        }
    }
}
