//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookARoom.ServiceReferenceCronus2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUS_Sverige_AB_Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUS_Sverige_AB_Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Post_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mobile_Phone_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string No_ {
            get {
                return this.No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.No_Field, value) != true)) {
                    this.No_Field = value;
                    this.RaisePropertyChanged("No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Address_2 {
            get {
                return this.Address_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address_2Field, value) != true)) {
                    this.Address_2Field = value;
                    this.RaisePropertyChanged("Address_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Post_Code {
            get {
                return this.Post_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Post_CodeField, value) != true)) {
                    this.Post_CodeField = value;
                    this.RaisePropertyChanged("Post_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Phone_No_ {
            get {
                return this.Phone_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone_No_Field, value) != true)) {
                    this.Phone_No_Field = value;
                    this.RaisePropertyChanged("Phone_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Mobile_Phone_No_ {
            get {
                return this.Mobile_Phone_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Mobile_Phone_No_Field, value) != true)) {
                    this.Mobile_Phone_No_Field = value;
                    this.RaisePropertyChanged("Mobile_Phone_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Key", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Key : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Constraint_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Constraint_Name {
            get {
                return this.Constraint_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Constraint_NameField, value) != true)) {
                    this.Constraint_NameField = value;
                    this.RaisePropertyChanged("Constraint_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Index", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Index : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Constraint", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Constraint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Constraint_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Table_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Constraint_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Constraint_Name {
            get {
                return this.Constraint_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Constraint_NameField, value) != true)) {
                    this.Constraint_NameField = value;
                    this.RaisePropertyChanged("Constraint_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Table_Name {
            get {
                return this.Table_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Table_NameField, value) != true)) {
                    this.Table_NameField = value;
                    this.RaisePropertyChanged("Table_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Constraint_Type {
            get {
                return this.Constraint_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Constraint_TypeField, value) != true)) {
                    this.Constraint_TypeField = value;
                    this.RaisePropertyChanged("Constraint_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Table", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Column", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Column : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Table_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Table_Name {
            get {
                return this.Table_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Table_NameField, value) != true)) {
                    this.Table_NameField = value;
                    this.RaisePropertyChanged("Table_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Column_Name {
            get {
                return this.Column_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Column_NameField, value) != true)) {
                    this.Column_NameField = value;
                    this.RaisePropertyChanged("Column_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_EmployeeRelated", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_EmployeeRelated : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TabellnamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tabellnamn {
            get {
                return this.TabellnamnField;
            }
            set {
                if ((object.ReferenceEquals(this.TabellnamnField, value) != true)) {
                    this.TabellnamnField = value;
                    this.RaisePropertyChanged("Tabellnamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUS_Employee_Top5_Absence", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUS_Employee_Top5_Absence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUS_Employees_And_Relatives", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUS_Employees_And_Relatives : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelativeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Relative {
            get {
                return this.RelativeField;
            }
            set {
                if ((object.ReferenceEquals(this.RelativeField, value) != true)) {
                    this.RelativeField = value;
                    this.RaisePropertyChanged("Relative");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUS_Employees_Sick_2004", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUS_Employees_Sick_2004 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        private System.DateTime From_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string From_DateStringField;
        
        private System.DateTime To_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string To_DateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cause_of_Absence_CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime From_Date {
            get {
                return this.From_DateField;
            }
            set {
                if ((this.From_DateField.Equals(value) != true)) {
                    this.From_DateField = value;
                    this.RaisePropertyChanged("From_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string From_DateString {
            get {
                return this.From_DateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.From_DateStringField, value) != true)) {
                    this.From_DateStringField = value;
                    this.RaisePropertyChanged("From_DateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime To_Date {
            get {
                return this.To_DateField;
            }
            set {
                if ((this.To_DateField.Equals(value) != true)) {
                    this.To_DateField = value;
                    this.RaisePropertyChanged("To_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string To_DateString {
            get {
                return this.To_DateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.To_DateStringField, value) != true)) {
                    this.To_DateStringField = value;
                    this.RaisePropertyChanged("To_DateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Cause_of_Absence_Code {
            get {
                return this.Cause_of_Absence_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cause_of_Absence_CodeField, value) != true)) {
                    this.Cause_of_Absence_CodeField = value;
                    this.RaisePropertyChanged("Cause_of_Absence_Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCronus2.CronusWebServiceSoap")]
    public interface CronusWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse GetAllEmployees(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse> GetAllEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllKeysResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllKeysResponse GetAllKeys(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllKeysResponse> GetAllKeysAsync(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllIndexesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse GetAllIndexes(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse> GetAllIndexesAsync(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse GetAllConstraints(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse> GetAllConstraintsAsync(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTablesInDBResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTablesInDB", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse GetAllTablesInDB(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTablesInDB", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse> GetAllTablesInDBAsync(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllColumnsInEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllColumnsInEmployees", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse GetAllColumnsInEmployees(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllColumnsInEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse> GetAllColumnsInEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeeMetaDataAndRelatedResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeMetaDataAndRelated", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponse GetEmployeeMetaDataAndRelated(BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeMetaDataAndRelated", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponse> GetEmployeeMetaDataAndRelatedAsync(BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest request);
        
        // CODEGEN: Generating message contract since element name GetTop5EmployeesAbsentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTop5EmployeesAbsent", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponse GetTop5EmployeesAbsent(BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTop5EmployeesAbsent", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponse> GetTop5EmployeesAbsentAsync(BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesAndRelativesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesAndRelatives", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponse GetEmployeesAndRelatives(BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesAndRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponse> GetEmployeesAndRelativesAsync(BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesSick2004Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesSick2004", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Response GetEmployeesSick2004(BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesSick2004", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Response> GetEmployeesSick2004Async(BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployees", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody Body;
        
        public GetAllEmployeesRequest() {
        }
        
        public GetAllEmployeesRequest(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEmployeesRequestBody {
        
        public GetAllEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponseBody Body;
        
        public GetAllEmployeesResponse() {
        }
        
        public GetAllEmployeesResponse(BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Sverige_AB_Employee> GetAllEmployeesResult;
        
        public GetAllEmployeesResponseBody() {
        }
        
        public GetAllEmployeesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Sverige_AB_Employee> GetAllEmployeesResult) {
            this.GetAllEmployeesResult = GetAllEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeys", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody Body;
        
        public GetAllKeysRequest() {
        }
        
        public GetAllKeysRequest(BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKeysRequestBody {
        
        public GetAllKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllKeysResponseBody Body;
        
        public GetAllKeysResponse() {
        }
        
        public GetAllKeysResponse(BookARoom.ServiceReferenceCronus2.GetAllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Key> GetAllKeysResult;
        
        public GetAllKeysResponseBody() {
        }
        
        public GetAllKeysResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Key> GetAllKeysResult) {
            this.GetAllKeysResult = GetAllKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexes", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody Body;
        
        public GetAllIndexesRequest() {
        }
        
        public GetAllIndexesRequest(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllIndexesRequestBody {
        
        public GetAllIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllIndexesResponseBody Body;
        
        public GetAllIndexesResponse() {
        }
        
        public GetAllIndexesResponse(BookARoom.ServiceReferenceCronus2.GetAllIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Index> GetAllIndexesResult;
        
        public GetAllIndexesResponseBody() {
        }
        
        public GetAllIndexesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Index> GetAllIndexesResult) {
            this.GetAllIndexesResult = GetAllIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraints", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody Body;
        
        public GetAllConstraintsRequest() {
        }
        
        public GetAllConstraintsRequest(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllConstraintsRequestBody {
        
        public GetAllConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponseBody Body;
        
        public GetAllConstraintsResponse() {
        }
        
        public GetAllConstraintsResponse(BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Constraint> GetAllConstraintsResult;
        
        public GetAllConstraintsResponseBody() {
        }
        
        public GetAllConstraintsResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Constraint> GetAllConstraintsResult) {
            this.GetAllConstraintsResult = GetAllConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesInDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesInDB", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody Body;
        
        public GetAllTablesInDBRequest() {
        }
        
        public GetAllTablesInDBRequest(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTablesInDBRequestBody {
        
        public GetAllTablesInDBRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesInDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesInDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponseBody Body;
        
        public GetAllTablesInDBResponse() {
        }
        
        public GetAllTablesInDBResponse(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTablesInDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Table> GetAllTablesInDBResult;
        
        public GetAllTablesInDBResponseBody() {
        }
        
        public GetAllTablesInDBResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Table> GetAllTablesInDBResult) {
            this.GetAllTablesInDBResult = GetAllTablesInDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsInEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsInEmployees", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody Body;
        
        public GetAllColumnsInEmployeesRequest() {
        }
        
        public GetAllColumnsInEmployeesRequest(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllColumnsInEmployeesRequestBody {
        
        public GetAllColumnsInEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsInEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsInEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponseBody Body;
        
        public GetAllColumnsInEmployeesResponse() {
        }
        
        public GetAllColumnsInEmployeesResponse(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllColumnsInEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Column> GetAllColumnsInEmployeesResult;
        
        public GetAllColumnsInEmployeesResponseBody() {
        }
        
        public GetAllColumnsInEmployeesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Column> GetAllColumnsInEmployeesResult) {
            this.GetAllColumnsInEmployeesResult = GetAllColumnsInEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeMetaDataAndRelatedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeMetaDataAndRelated", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequestBody Body;
        
        public GetEmployeeMetaDataAndRelatedRequest() {
        }
        
        public GetEmployeeMetaDataAndRelatedRequest(BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeMetaDataAndRelatedRequestBody {
        
        public GetEmployeeMetaDataAndRelatedRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeMetaDataAndRelatedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeMetaDataAndRelatedResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponseBody Body;
        
        public GetEmployeeMetaDataAndRelatedResponse() {
        }
        
        public GetEmployeeMetaDataAndRelatedResponse(BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeMetaDataAndRelatedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_EmployeeRelated> GetEmployeeMetaDataAndRelatedResult;
        
        public GetEmployeeMetaDataAndRelatedResponseBody() {
        }
        
        public GetEmployeeMetaDataAndRelatedResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_EmployeeRelated> GetEmployeeMetaDataAndRelatedResult) {
            this.GetEmployeeMetaDataAndRelatedResult = GetEmployeeMetaDataAndRelatedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTop5EmployeesAbsentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTop5EmployeesAbsent", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequestBody Body;
        
        public GetTop5EmployeesAbsentRequest() {
        }
        
        public GetTop5EmployeesAbsentRequest(BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTop5EmployeesAbsentRequestBody {
        
        public GetTop5EmployeesAbsentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTop5EmployeesAbsentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTop5EmployeesAbsentResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponseBody Body;
        
        public GetTop5EmployeesAbsentResponse() {
        }
        
        public GetTop5EmployeesAbsentResponse(BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTop5EmployeesAbsentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employee_Top5_Absence> GetTop5EmployeesAbsentResult;
        
        public GetTop5EmployeesAbsentResponseBody() {
        }
        
        public GetTop5EmployeesAbsentResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employee_Top5_Absence> GetTop5EmployeesAbsentResult) {
            this.GetTop5EmployeesAbsentResult = GetTop5EmployeesAbsentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesAndRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesAndRelatives", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequestBody Body;
        
        public GetEmployeesAndRelativesRequest() {
        }
        
        public GetEmployeesAndRelativesRequest(BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesAndRelativesRequestBody {
        
        public GetEmployeesAndRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesAndRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesAndRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponseBody Body;
        
        public GetEmployeesAndRelativesResponse() {
        }
        
        public GetEmployeesAndRelativesResponse(BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesAndRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employees_And_Relatives> GetEmployeesAndRelativesResult;
        
        public GetEmployeesAndRelativesResponseBody() {
        }
        
        public GetEmployeesAndRelativesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employees_And_Relatives> GetEmployeesAndRelativesResult) {
            this.GetEmployeesAndRelativesResult = GetEmployeesAndRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesSick2004Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesSick2004", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004RequestBody Body;
        
        public GetEmployeesSick2004Request() {
        }
        
        public GetEmployeesSick2004Request(BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesSick2004RequestBody {
        
        public GetEmployeesSick2004RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesSick2004Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesSick2004Response", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004ResponseBody Body;
        
        public GetEmployeesSick2004Response() {
        }
        
        public GetEmployeesSick2004Response(BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesSick2004ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employees_Sick_2004> GetEmployeesSick2004Result;
        
        public GetEmployeesSick2004ResponseBody() {
        }
        
        public GetEmployeesSick2004ResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employees_Sick_2004> GetEmployeesSick2004Result) {
            this.GetEmployeesSick2004Result = GetEmployeesSick2004Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CronusWebServiceSoapChannel : BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CronusWebServiceSoapClient : System.ServiceModel.ClientBase<BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap>, BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap {
        
        public CronusWebServiceSoapClient() {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllEmployees(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployees(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Sverige_AB_Employee> GetAllEmployees() {
            BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllEmployees(inValue);
            return retVal.Body.GetAllEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse> GetAllEmployeesAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllKeysResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllKeys(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request) {
            return base.Channel.GetAllKeys(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Key> GetAllKeys() {
            BookARoom.ServiceReferenceCronus2.GetAllKeysRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllKeysResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllKeys(inValue);
            return retVal.Body.GetAllKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllKeysResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllKeysAsync(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request) {
            return base.Channel.GetAllKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllKeysResponse> GetAllKeysAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllKeysRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllIndexes(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexes(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Index> GetAllIndexes() {
            BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllIndexes(inValue);
            return retVal.Body.GetAllIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllIndexesAsync(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse> GetAllIndexesAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllConstraints(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraints(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Constraint> GetAllConstraints() {
            BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllConstraints(inValue);
            return retVal.Body.GetAllConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllConstraintsAsync(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse> GetAllConstraintsAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllTablesInDB(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request) {
            return base.Channel.GetAllTablesInDB(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Table> GetAllTablesInDB() {
            BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllTablesInDB(inValue);
            return retVal.Body.GetAllTablesInDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllTablesInDBAsync(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request) {
            return base.Channel.GetAllTablesInDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse> GetAllTablesInDBAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllTablesInDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllColumnsInEmployees(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request) {
            return base.Channel.GetAllColumnsInEmployees(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Column> GetAllColumnsInEmployees() {
            BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllColumnsInEmployees(inValue);
            return retVal.Body.GetAllColumnsInEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllColumnsInEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request) {
            return base.Channel.GetAllColumnsInEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse> GetAllColumnsInEmployeesAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllColumnsInEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetEmployeeMetaDataAndRelated(BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest request) {
            return base.Channel.GetEmployeeMetaDataAndRelated(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_EmployeeRelated> GetEmployeeMetaDataAndRelated() {
            BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest inValue = new BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequestBody();
            BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetEmployeeMetaDataAndRelated(inValue);
            return retVal.Body.GetEmployeeMetaDataAndRelatedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetEmployeeMetaDataAndRelatedAsync(BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest request) {
            return base.Channel.GetEmployeeMetaDataAndRelatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedResponse> GetEmployeeMetaDataAndRelatedAsync() {
            BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest inValue = new BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetEmployeeMetaDataAndRelatedRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetEmployeeMetaDataAndRelatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetTop5EmployeesAbsent(BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest request) {
            return base.Channel.GetTop5EmployeesAbsent(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employee_Top5_Absence> GetTop5EmployeesAbsent() {
            BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest inValue = new BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequestBody();
            BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetTop5EmployeesAbsent(inValue);
            return retVal.Body.GetTop5EmployeesAbsentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetTop5EmployeesAbsentAsync(BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest request) {
            return base.Channel.GetTop5EmployeesAbsentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentResponse> GetTop5EmployeesAbsentAsync() {
            BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest inValue = new BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetTop5EmployeesAbsentRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetTop5EmployeesAbsentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetEmployeesAndRelatives(BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest request) {
            return base.Channel.GetEmployeesAndRelatives(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employees_And_Relatives> GetEmployeesAndRelatives() {
            BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequestBody();
            BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetEmployeesAndRelatives(inValue);
            return retVal.Body.GetEmployeesAndRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetEmployeesAndRelativesAsync(BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest request) {
            return base.Channel.GetEmployeesAndRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesResponse> GetEmployeesAndRelativesAsync() {
            BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetEmployeesAndRelativesRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetEmployeesAndRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Response BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetEmployeesSick2004(BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request request) {
            return base.Channel.GetEmployeesSick2004(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Employees_Sick_2004> GetEmployeesSick2004() {
            BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request inValue = new BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004RequestBody();
            BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Response retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetEmployeesSick2004(inValue);
            return retVal.Body.GetEmployeesSick2004Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Response> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetEmployeesSick2004Async(BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request request) {
            return base.Channel.GetEmployeesSick2004Async(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Response> GetEmployeesSick2004Async() {
            BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request inValue = new BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004Request();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetEmployeesSick2004RequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetEmployeesSick2004Async(inValue);
        }
    }
}
