//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookARoom.ServiceReferenceCronus2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUS_Sverige_AB_Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUS_Sverige_AB_Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Middle_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Search_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Post_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mobile_Phone_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Alt__Address_CodeField;
        
        private System.DateTime Alt__Address_Start_DateField;
        
        private System.DateTime Alt__Address_End_DateField;
        
        private System.DateTime Birth_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Social_Security_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Union_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Union_Membership_No_Field;
        
        private int SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Country_Region_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Manager_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emplymt__Contract_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Statistics_Group_CodeField;
        
        private System.DateTime Employment_DateField;
        
        private int StatusField;
        
        private System.DateTime Inactive_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cause_of_Inactivity_CodeField;
        
        private System.DateTime Termination_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Grounds_for_Term__CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Global_Dimension_1_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Global_Dimension_2_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Resource_No_Field;
        
        private System.DateTime Last_Date_ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fax_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Company_E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Salespers__Purch__CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string No__SeriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string No_ {
            get {
                return this.No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.No_Field, value) != true)) {
                    this.No_Field = value;
                    this.RaisePropertyChanged("No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Middle_Name {
            get {
                return this.Middle_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Middle_NameField, value) != true)) {
                    this.Middle_NameField = value;
                    this.RaisePropertyChanged("Middle_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Search_Name {
            get {
                return this.Search_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Search_NameField, value) != true)) {
                    this.Search_NameField = value;
                    this.RaisePropertyChanged("Search_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Address_2 {
            get {
                return this.Address_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address_2Field, value) != true)) {
                    this.Address_2Field = value;
                    this.RaisePropertyChanged("Address_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Post_Code {
            get {
                return this.Post_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Post_CodeField, value) != true)) {
                    this.Post_CodeField = value;
                    this.RaisePropertyChanged("Post_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Phone_No_ {
            get {
                return this.Phone_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone_No_Field, value) != true)) {
                    this.Phone_No_Field = value;
                    this.RaisePropertyChanged("Phone_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Mobile_Phone_No_ {
            get {
                return this.Mobile_Phone_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Mobile_Phone_No_Field, value) != true)) {
                    this.Mobile_Phone_No_Field = value;
                    this.RaisePropertyChanged("Mobile_Phone_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Alt__Address_Code {
            get {
                return this.Alt__Address_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Alt__Address_CodeField, value) != true)) {
                    this.Alt__Address_CodeField = value;
                    this.RaisePropertyChanged("Alt__Address_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.DateTime Alt__Address_Start_Date {
            get {
                return this.Alt__Address_Start_DateField;
            }
            set {
                if ((this.Alt__Address_Start_DateField.Equals(value) != true)) {
                    this.Alt__Address_Start_DateField = value;
                    this.RaisePropertyChanged("Alt__Address_Start_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime Alt__Address_End_Date {
            get {
                return this.Alt__Address_End_DateField;
            }
            set {
                if ((this.Alt__Address_End_DateField.Equals(value) != true)) {
                    this.Alt__Address_End_DateField = value;
                    this.RaisePropertyChanged("Alt__Address_End_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.DateTime Birth_Date {
            get {
                return this.Birth_DateField;
            }
            set {
                if ((this.Birth_DateField.Equals(value) != true)) {
                    this.Birth_DateField = value;
                    this.RaisePropertyChanged("Birth_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Social_Security_No_ {
            get {
                return this.Social_Security_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Social_Security_No_Field, value) != true)) {
                    this.Social_Security_No_Field = value;
                    this.RaisePropertyChanged("Social_Security_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Union_Code {
            get {
                return this.Union_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Union_CodeField, value) != true)) {
                    this.Union_CodeField = value;
                    this.RaisePropertyChanged("Union_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Union_Membership_No_ {
            get {
                return this.Union_Membership_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Union_Membership_No_Field, value) != true)) {
                    this.Union_Membership_No_Field = value;
                    this.RaisePropertyChanged("Union_Membership_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Country_Region_Code {
            get {
                return this.Country_Region_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Country_Region_CodeField, value) != true)) {
                    this.Country_Region_CodeField = value;
                    this.RaisePropertyChanged("Country_Region_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Manager_No_ {
            get {
                return this.Manager_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Manager_No_Field, value) != true)) {
                    this.Manager_No_Field = value;
                    this.RaisePropertyChanged("Manager_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Emplymt__Contract_Code {
            get {
                return this.Emplymt__Contract_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Emplymt__Contract_CodeField, value) != true)) {
                    this.Emplymt__Contract_CodeField = value;
                    this.RaisePropertyChanged("Emplymt__Contract_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string Statistics_Group_Code {
            get {
                return this.Statistics_Group_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Statistics_Group_CodeField, value) != true)) {
                    this.Statistics_Group_CodeField = value;
                    this.RaisePropertyChanged("Statistics_Group_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public System.DateTime Employment_Date {
            get {
                return this.Employment_DateField;
            }
            set {
                if ((this.Employment_DateField.Equals(value) != true)) {
                    this.Employment_DateField = value;
                    this.RaisePropertyChanged("Employment_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.DateTime Inactive_Date {
            get {
                return this.Inactive_DateField;
            }
            set {
                if ((this.Inactive_DateField.Equals(value) != true)) {
                    this.Inactive_DateField = value;
                    this.RaisePropertyChanged("Inactive_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string Cause_of_Inactivity_Code {
            get {
                return this.Cause_of_Inactivity_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cause_of_Inactivity_CodeField, value) != true)) {
                    this.Cause_of_Inactivity_CodeField = value;
                    this.RaisePropertyChanged("Cause_of_Inactivity_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public System.DateTime Termination_Date {
            get {
                return this.Termination_DateField;
            }
            set {
                if ((this.Termination_DateField.Equals(value) != true)) {
                    this.Termination_DateField = value;
                    this.RaisePropertyChanged("Termination_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string Grounds_for_Term__Code {
            get {
                return this.Grounds_for_Term__CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Grounds_for_Term__CodeField, value) != true)) {
                    this.Grounds_for_Term__CodeField = value;
                    this.RaisePropertyChanged("Grounds_for_Term__Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string Global_Dimension_1_Code {
            get {
                return this.Global_Dimension_1_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Global_Dimension_1_CodeField, value) != true)) {
                    this.Global_Dimension_1_CodeField = value;
                    this.RaisePropertyChanged("Global_Dimension_1_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string Global_Dimension_2_Code {
            get {
                return this.Global_Dimension_2_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Global_Dimension_2_CodeField, value) != true)) {
                    this.Global_Dimension_2_CodeField = value;
                    this.RaisePropertyChanged("Global_Dimension_2_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string Resource_No_ {
            get {
                return this.Resource_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Resource_No_Field, value) != true)) {
                    this.Resource_No_Field = value;
                    this.RaisePropertyChanged("Resource_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public System.DateTime Last_Date_Modified {
            get {
                return this.Last_Date_ModifiedField;
            }
            set {
                if ((this.Last_Date_ModifiedField.Equals(value) != true)) {
                    this.Last_Date_ModifiedField = value;
                    this.RaisePropertyChanged("Last_Date_Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string Pager {
            get {
                return this.PagerField;
            }
            set {
                if ((object.ReferenceEquals(this.PagerField, value) != true)) {
                    this.PagerField = value;
                    this.RaisePropertyChanged("Pager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string Fax_No_ {
            get {
                return this.Fax_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fax_No_Field, value) != true)) {
                    this.Fax_No_Field = value;
                    this.RaisePropertyChanged("Fax_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string Company_E_Mail {
            get {
                return this.Company_E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.Company_E_MailField, value) != true)) {
                    this.Company_E_MailField = value;
                    this.RaisePropertyChanged("Company_E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string Salespers__Purch__Code {
            get {
                return this.Salespers__Purch__CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Salespers__Purch__CodeField, value) != true)) {
                    this.Salespers__Purch__CodeField = value;
                    this.RaisePropertyChanged("Salespers__Purch__Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string No__Series {
            get {
                return this.No__SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.No__SeriesField, value) != true)) {
                    this.No__SeriesField = value;
                    this.RaisePropertyChanged("No__Series");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Key", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Key : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Constraint_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Constraint_Name {
            get {
                return this.Constraint_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Constraint_NameField, value) != true)) {
                    this.Constraint_NameField = value;
                    this.RaisePropertyChanged("Constraint_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Index", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Index : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Constraint", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Constraint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Constraint_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Table_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Constraint_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Constraint_Name {
            get {
                return this.Constraint_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Constraint_NameField, value) != true)) {
                    this.Constraint_NameField = value;
                    this.RaisePropertyChanged("Constraint_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Table_Name {
            get {
                return this.Table_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Table_NameField, value) != true)) {
                    this.Table_NameField = value;
                    this.RaisePropertyChanged("Table_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Constraint_Type {
            get {
                return this.Constraint_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Constraint_TypeField, value) != true)) {
                    this.Constraint_TypeField = value;
                    this.RaisePropertyChanged("Constraint_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Table", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRONUSMetadata_Column", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRONUSMetadata_Column : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Table_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Table_Name {
            get {
                return this.Table_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Table_NameField, value) != true)) {
                    this.Table_NameField = value;
                    this.RaisePropertyChanged("Table_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Column_Name {
            get {
                return this.Column_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Column_NameField, value) != true)) {
                    this.Column_NameField = value;
                    this.RaisePropertyChanged("Column_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCronus2.CronusWebServiceSoap")]
    public interface CronusWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse GetAllEmployees(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse> GetAllEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllKeysResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllKeysResponse GetAllKeys(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllKeysResponse> GetAllKeysAsync(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllIndexesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse GetAllIndexes(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse> GetAllIndexesAsync(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse GetAllConstraints(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse> GetAllConstraintsAsync(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTablesInDBResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTablesInDB", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse GetAllTablesInDB(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTablesInDB", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse> GetAllTablesInDBAsync(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllColumnsInEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllColumnsInEmployees", ReplyAction="*")]
        BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse GetAllColumnsInEmployees(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllColumnsInEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse> GetAllColumnsInEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployees", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody Body;
        
        public GetAllEmployeesRequest() {
        }
        
        public GetAllEmployeesRequest(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEmployeesRequestBody {
        
        public GetAllEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponseBody Body;
        
        public GetAllEmployeesResponse() {
        }
        
        public GetAllEmployeesResponse(BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Sverige_AB_Employee> GetAllEmployeesResult;
        
        public GetAllEmployeesResponseBody() {
        }
        
        public GetAllEmployeesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Sverige_AB_Employee> GetAllEmployeesResult) {
            this.GetAllEmployeesResult = GetAllEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeys", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody Body;
        
        public GetAllKeysRequest() {
        }
        
        public GetAllKeysRequest(BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKeysRequestBody {
        
        public GetAllKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllKeysResponseBody Body;
        
        public GetAllKeysResponse() {
        }
        
        public GetAllKeysResponse(BookARoom.ServiceReferenceCronus2.GetAllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Key> GetAllKeysResult;
        
        public GetAllKeysResponseBody() {
        }
        
        public GetAllKeysResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Key> GetAllKeysResult) {
            this.GetAllKeysResult = GetAllKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexes", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody Body;
        
        public GetAllIndexesRequest() {
        }
        
        public GetAllIndexesRequest(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllIndexesRequestBody {
        
        public GetAllIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllIndexesResponseBody Body;
        
        public GetAllIndexesResponse() {
        }
        
        public GetAllIndexesResponse(BookARoom.ServiceReferenceCronus2.GetAllIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Index> GetAllIndexesResult;
        
        public GetAllIndexesResponseBody() {
        }
        
        public GetAllIndexesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Index> GetAllIndexesResult) {
            this.GetAllIndexesResult = GetAllIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraints", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody Body;
        
        public GetAllConstraintsRequest() {
        }
        
        public GetAllConstraintsRequest(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllConstraintsRequestBody {
        
        public GetAllConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponseBody Body;
        
        public GetAllConstraintsResponse() {
        }
        
        public GetAllConstraintsResponse(BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Constraint> GetAllConstraintsResult;
        
        public GetAllConstraintsResponseBody() {
        }
        
        public GetAllConstraintsResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Constraint> GetAllConstraintsResult) {
            this.GetAllConstraintsResult = GetAllConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesInDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesInDB", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody Body;
        
        public GetAllTablesInDBRequest() {
        }
        
        public GetAllTablesInDBRequest(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTablesInDBRequestBody {
        
        public GetAllTablesInDBRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesInDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesInDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponseBody Body;
        
        public GetAllTablesInDBResponse() {
        }
        
        public GetAllTablesInDBResponse(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTablesInDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Table> GetAllTablesInDBResult;
        
        public GetAllTablesInDBResponseBody() {
        }
        
        public GetAllTablesInDBResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Table> GetAllTablesInDBResult) {
            this.GetAllTablesInDBResult = GetAllTablesInDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsInEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsInEmployees", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody Body;
        
        public GetAllColumnsInEmployeesRequest() {
        }
        
        public GetAllColumnsInEmployeesRequest(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllColumnsInEmployeesRequestBody {
        
        public GetAllColumnsInEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsInEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsInEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponseBody Body;
        
        public GetAllColumnsInEmployeesResponse() {
        }
        
        public GetAllColumnsInEmployeesResponse(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllColumnsInEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Column> GetAllColumnsInEmployeesResult;
        
        public GetAllColumnsInEmployeesResponseBody() {
        }
        
        public GetAllColumnsInEmployeesResponseBody(System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Column> GetAllColumnsInEmployeesResult) {
            this.GetAllColumnsInEmployeesResult = GetAllColumnsInEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CronusWebServiceSoapChannel : BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CronusWebServiceSoapClient : System.ServiceModel.ClientBase<BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap>, BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap {
        
        public CronusWebServiceSoapClient() {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllEmployees(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployees(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUS_Sverige_AB_Employee> GetAllEmployees() {
            BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllEmployees(inValue);
            return retVal.Body.GetAllEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllEmployeesResponse> GetAllEmployeesAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllEmployeesRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllKeysResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllKeys(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request) {
            return base.Channel.GetAllKeys(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Key> GetAllKeys() {
            BookARoom.ServiceReferenceCronus2.GetAllKeysRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllKeysResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllKeys(inValue);
            return retVal.Body.GetAllKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllKeysResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllKeysAsync(BookARoom.ServiceReferenceCronus2.GetAllKeysRequest request) {
            return base.Channel.GetAllKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllKeysResponse> GetAllKeysAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllKeysRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllKeysRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllIndexes(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexes(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Index> GetAllIndexes() {
            BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllIndexes(inValue);
            return retVal.Body.GetAllIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllIndexesAsync(BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllIndexesResponse> GetAllIndexesAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllIndexesRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllConstraints(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraints(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Constraint> GetAllConstraints() {
            BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllConstraints(inValue);
            return retVal.Body.GetAllConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllConstraintsAsync(BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllConstraintsResponse> GetAllConstraintsAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllConstraintsRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllTablesInDB(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request) {
            return base.Channel.GetAllTablesInDB(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Table> GetAllTablesInDB() {
            BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllTablesInDB(inValue);
            return retVal.Body.GetAllTablesInDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllTablesInDBAsync(BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest request) {
            return base.Channel.GetAllTablesInDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllTablesInDBResponse> GetAllTablesInDBAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllTablesInDBRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllTablesInDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllColumnsInEmployees(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request) {
            return base.Channel.GetAllColumnsInEmployees(request);
        }
        
        public System.Collections.Generic.List<BookARoom.ServiceReferenceCronus2.CRONUSMetadata_Column> GetAllColumnsInEmployees() {
            BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody();
            BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse retVal = ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllColumnsInEmployees(inValue);
            return retVal.Body.GetAllColumnsInEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse> BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap.GetAllColumnsInEmployeesAsync(BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest request) {
            return base.Channel.GetAllColumnsInEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesResponse> GetAllColumnsInEmployeesAsync() {
            BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest inValue = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequest();
            inValue.Body = new BookARoom.ServiceReferenceCronus2.GetAllColumnsInEmployeesRequestBody();
            return ((BookARoom.ServiceReferenceCronus2.CronusWebServiceSoap)(this)).GetAllColumnsInEmployeesAsync(inValue);
        }
    }
}
